# Generated by Django 5.2.6 on 2025-09-07 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_songs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='title',
            new_name='name_song',
        ),
    ]
