# Generated by Django 5.2.6 on 2025-09-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_rename_title_songs_name_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='songs',
            name='video',
            field=models.URLField(default='https://youtube.com'),
        ),
    ]
