# Generated by Django 5.2.6 on 2025-09-07 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_songs_duration_songs_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
